### PR TITLE
refactor: Updated to Swift 3 and Xcode 8

### PR DESCRIPTION
**Pull request by omaralbeik**
Updated to latest swift 3 and Xcode 8

### CODE REVIEW

**Comment by omaralbeik** [comment]
how about combining the GaugeView.swift and GaugeLayer int one file, so users don't have to copy two files when installing manually?

**Comment by GnuRant** [comment]
Hey, you should use Cocoapods to install this pod into your project, btw in my opinion the code should be splitted in a logical way in order to improve the code readability and maintainability. Do you suggest a better way to structure the code ?

**Comment by omaralbeik** [comment]
@GnuRant I totally agree with you!
split the file into multiple parts, but since the GaugeLayer is private, I think It's better to add it into GaugeView.swift file and keep it separated from the GaugeView class
You can have multiple classes in one .swift file, also extension is a great way to organize code
Thank you!

**Comment by GnuRant** [comment]
@omaralbeik thanks for the suggestions, I reject your pull request because I want to deeply understand if there is a better way to write the component in swift 3. 
Thanks for the support!

**Pull request closed without merging**
